[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spanish_tools"
version = "0.1.0"
description = "A Python library for Spanish data analysis complexities."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
data = ["pandas"]

[project.urls]
"Homepage" = "https://github.com/AleLoredo/spanish-tools"
